# Generated by Django 4.2.7 on 2023-12-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
